server:
  port: 8888
spring:
  application:
    name: mszlu

#  数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mszl-blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: ms_